# -*- coding: utf-8 -*-
"""plot the excel file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NINlbJJfqarMHuMUAPFyyfCSsHiZAWv-
"""

import pandas as pd
df = pd.DataFrame({'GOOD 1':[34,17,47,31,20,64,72],
                   'GOOD 2':[12,29,19,82,65,74,50],
                   'GOOD3':[47,78,54,98,96,36,12],
                   'GOOD4':[91,63,80,55,78,89,93],
                   'GOOD5':[87,83,56,81,11,34,94]})
index = pd.Index(['vender 1','vender 2','vender3','vender 4','vender 5','vender 6','vender 7'])
df = df.set_index(index)
df

import seaborn as sns
import matplotlib.pyplot as plt
sns.heatmap(df, annot=True, cmap='YlGnBu')
plt.title('Heatmap')
plt.xlabel('GOODS')
plt.ylabel('Vendors')
plt.show()

df1 = pd.read_excel('/content/drive/MyDrive/Case studies4.xlsx')
df1

sns.heatmap(df1, annot=True, cmap='YlGnBu')
plt.title('Heatmap')
plt.xlabel('GOODS')
plt.ylabel('Vendors')
plt.show()

import matplotlib.pyplot as plt
df1.plot(kind='bar')
plt.title('Bar Graph')
plt.xlabel('x')
plt.ylabel('y')
plt.show()